-- Tabla temporal para common_player_info
CREATE TABLE common_player_info_temp (
    person_id VARCHAR2(255),
    first_name VARCHAR2(255),
    last_name VARCHAR2(255),
    display_first_last VARCHAR2(255),
    display_last_comma_first VARCHAR2(255),
    display_fi_last VARCHAR2(255),
    player_slug VARCHAR2(255),
    birthdate TIMESTAMP,
    school VARCHAR2(255),
    country VARCHAR2(255),
    last_affiliation VARCHAR2(255),
    height VARCHAR2(255),
    weight VARCHAR2(255),
    season_exp NUMBER,
    jersey VARCHAR2(255),
    position_ VARCHAR2(255),
    rosterstatus VARCHAR2(255),
    games_played_current_season_flag VARCHAR2(255),
    team_id NUMBER,
    team_name VARCHAR2(255),
    team_abbreviation VARCHAR2(255),
    team_code VARCHAR2(255),
    team_city VARCHAR2(255),
    playercode VARCHAR2(255),
    from_year NUMBER,
    to_year NUMBER,
    dleague_flag VARCHAR2(255),
    nba_flag VARCHAR2(255),
    games_played_flag VARCHAR2(255),
    draft_year VARCHAR2(255),
    draft_round VARCHAR2(255),
    draft_number VARCHAR2(255),
    greatest_75_flag VARCHAR2(255)
);

-- Tabla temporal para draft_combine_stats
CREATE TABLE draft_combine_stats_temp (
    season VARCHAR2(255),
    player_id VARCHAR2(255),
    first_name VARCHAR2(255),
    last_name VARCHAR2(255),
    player_name VARCHAR2(255),
    position_ VARCHAR2(255),
    height_wo_shoes NUMBER,
    height_wo_shoes_ft_in VARCHAR2(255),
    height_w_shoes NUMBER,
    height_w_shoes_ft_in VARCHAR2(255),
    weight VARCHAR2(255),
    wingspan NUMBER,
    wingspan_ft_in VARCHAR2(255),
    standing_reach NUMBER,
    standing_reach_ft_in VARCHAR2(255),
    body_fat_pct VARCHAR2(255),
    hand_length VARCHAR2(255),
    hand_width VARCHAR2(255),
    standing_vertical_leap NUMBER,
    max_vertical_leap NUMBER,
    lane_agility_time NUMBER,
    modified_lane_agility_time NUMBER,
    three_quarter_sprint NUMBER,
    bench_press NUMBER,
    spot_fifteen_corner_left VARCHAR2(255),
    spot_fifteen_break_left VARCHAR2(255),
    spot_fifteen_top_key VARCHAR2(255),
    spot_fifteen_break_right VARCHAR2(255),
    spot_fifteen_corner_right VARCHAR2(255),
    spot_college_corner_left VARCHAR2(255),
    spot_college_break_left VARCHAR2(255),
    spot_college_top_key VARCHAR2(255),
    spot_college_break_right VARCHAR2(255),
    spot_college_corner_right VARCHAR2(255),
    spot_nba_corner_left VARCHAR2(255),
    spot_nba_break_left VARCHAR2(255),
    spot_nba_top_key VARCHAR2(255),
    spot_nba_break_right VARCHAR2(255),
    spot_nba_corner_right VARCHAR2(255),
    off_drib_fifteen_break_left VARCHAR2(255),
    off_drib_fifteen_top_key VARCHAR2(255),
    off_drib_fifteen_break_right VARCHAR2(255),
    off_drib_college_break_left VARCHAR2(255),
    off_drib_college_top_key VARCHAR2(255),
    off_drib_college_break_right VARCHAR2(255),
    on_move_fifteen VARCHAR2(255),
    on_move_college VARCHAR2(255)
);

-- Tabla temporal para draft_history
CREATE TABLE draft_history_temp (
    person_id VARCHAR2(255),
    player_name VARCHAR2(255),
    season VARCHAR2(255),
    round_number NUMBER,
    round_pick NUMBER,
    overall_pick NUMBER,
    draft_type VARCHAR2(255),
    team_id VARCHAR2(255),
    team_city VARCHAR2(255),
    team_name VARCHAR2(255),
    team_abbreviation VARCHAR2(255),
    organization_ VARCHAR2(255),
    organization_type VARCHAR2(255),
    player_profile_flag VARCHAR2(255)
);

-- Tabla temporal para game
CREATE TABLE game_temp (
    season_id VARCHAR2(255),
    team_id_home VARCHAR2(255),
    team_abbreviation_home VARCHAR2(255),
    team_name_home VARCHAR2(255),
    game_id VARCHAR2(255),
    game_date TIMESTAMP,
    matchup_home VARCHAR2(255),
    wl_home VARCHAR2(255),
    min_ NUMBER,
    fgm_home NUMBER,
    fga_home NUMBER,
    fg_pct_home NUMBER,
    fg3m_home NUMBER,
    fg3a_home NUMBER,
    fg3_pct_home NUMBER,
    ftm_home NUMBER,
    fta_home NUMBER,
    ft_pct_home NUMBER,
    oreb_home NUMBER,
    dreb_home NUMBER,
    reb_home NUMBER,
    ast_home NUMBER,
    stl_home NUMBER,
    blk_home NUMBER,
    tov_home NUMBER,
    pf_home NUMBER,
    pts_home NUMBER,
    plus_minus_home NUMBER,
    video_available_home NUMBER,
    team_id_away VARCHAR2(255),
    team_abbreviation_away VARCHAR2(255),
    team_name_away VARCHAR2(255),
    matchup_away VARCHAR2(255),
    wl_away VARCHAR2(255),
    fgm_away NUMBER,
    fga_away NUMBER,
    fg_pct_away NUMBER,
    fg3m_away NUMBER,
    fg3a_away NUMBER,
    fg3_pct_away NUMBER,
    ftm_away NUMBER,
    fta_away NUMBER,
    ft_pct_away NUMBER,
    oreb_away NUMBER,
    dreb_away NUMBER,
    reb_away NUMBER,
    ast_away NUMBER,
    stl_away NUMBER,
    blk_away NUMBER,
    tov_away NUMBER,
    pf_away NUMBER,
    pts_away NUMBER,
    plus_minus_away NUMBER,
    video_available_away NUMBER,
    season_type VARCHAR2(255)
);

-- Tabla temporal para game_info
CREATE TABLE game_info_temp (
    game_id VARCHAR2(255),
    game_date TIMESTAMP,
    attendance NUMBER,
    game_time VARCHAR2(255)
);

-- Tabla temporal para game_summary
CREATE TABLE game_summary_temp (
    game_date_est TIMESTAMP,
    game_sequence NUMBER,
    game_id VARCHAR2(255),
    game_status_id NUMBER,
    game_status_text VARCHAR2(255),
    gamecode VARCHAR2(255),
    home_team_id VARCHAR2(255),
    visitor_team_id VARCHAR2(255),
    season VARCHAR2(255),
    live_period NUMBER,
    live_pc_time VARCHAR2(255),
    natl_tv_broadcaster_abbreviation VARCHAR2(255),
    live_period_time_bcast VARCHAR2(255),
    wh_status NUMBER
);

-- Tabla temporal para inactive_players
CREATE TABLE inactive_players_temp (
    game_id VARCHAR2(255),
    player_id VARCHAR2(255),
    first_name VARCHAR2(255),
    last_name VARCHAR2(255),
    jersey_num VARCHAR2(255),
    team_id VARCHAR2(255),
    team_city VARCHAR2(255),
    team_name VARCHAR2(255),
    team_abbreviation VARCHAR2(255)
);

-- Tabla temporal para line_score
CREATE TABLE line_score_temp (
    game_date_est TIMESTAMP,
    game_sequence NUMBER,
    game_id VARCHAR2(255),
    team_id_home VARCHAR2(255),
    team_abbreviation_home VARCHAR2(255),
    team_city_name_home VARCHAR2(255),
    team_nickname_home VARCHAR2(255),
    team_wins_losses_home VARCHAR2(255),
    pts_qtr1_home VARCHAR2(255),
    pts_qtr2_home VARCHAR2(255),
    pts_qtr3_home VARCHAR2(255),
    pts_qtr4_home VARCHAR2(255),
    pts_ot1_home NUMBER,
    pts_ot2_home NUMBER,
    pts_ot3_home NUMBER,
    pts_ot4_home NUMBER,
    pts_ot5_home NUMBER,
    pts_ot6_home NUMBER,
    pts_ot7_home NUMBER,
    pts_ot8_home NUMBER,
    pts_ot9_home NUMBER,
    pts_ot10_home NUMBER,
    pts_home NUMBER,
    team_id_away VARCHAR2(255),
    team_abbreviation_away VARCHAR2(255),
    team_city_name_away VARCHAR2(255),
    team_nickname_away VARCHAR2(255),
    team_wins_losses_away VARCHAR2(255),
    pts_qtr1_away NUMBER,
    pts_qtr2_away VARCHAR2(255),
    pts_qtr3_away VARCHAR2(255),
    pts_qtr4_away NUMBER,
    pts_ot1_away NUMBER,
    pts_ot2_away NUMBER,
    pts_ot3_away NUMBER,
    pts_ot4_away NUMBER,
    pts_ot5_away NUMBER,
    pts_ot6_away NUMBER,
    pts_ot7_away NUMBER,
    pts_ot8_away NUMBER,
    pts_ot9_away NUMBER,
    pts_ot10_away NUMBER,
    pts_away NUMBER
);

-- Tabla temporal para officials
CREATE TABLE officials_temp (
    game_id VARCHAR2(255),
    official_id VARCHAR2(255),
    first_name VARCHAR2(255),
    last_name VARCHAR2(255),
    jersey_num VARCHAR2(255)
);

-- Tabla temporal para other_stats
CREATE TABLE other_stats_temp (
    game_id VARCHAR2(255),
    league_id VARCHAR2(255),
    team_id_home VARCHAR2(255),
    team_abbreviation_home VARCHAR2(255),
    team_city_home VARCHAR2(255),
    pts_paint_home NUMBER,
    pts_2nd_chance_home NUMBER,
    pts_fb_home NUMBER,
    largest_lead_home NUMBER,
    lead_changes NUMBER,
    times_tied NUMBER,
    team_turnovers_home NUMBER,
    total_turnovers_home NUMBER,
    team_rebounds_home NUMBER,
    pts_off_to_home NUMBER,
    team_id_away VARCHAR2(255),
    team_abbreviation_away VARCHAR2(255),
    team_city_away VARCHAR2(255),
    pts_paint_away NUMBER,
    pts_2nd_chance_away NUMBER,
    pts_fb_away NUMBER,
    largest_lead_away NUMBER,
    team_turnovers_away NUMBER,
    total_turnovers_away NUMBER,
    team_rebounds_away NUMBER,
    pts_off_to_away NUMBER
);

-- Tabla temporal para play_by_play
CREATE TABLE play_by_play_temp (
    game_id VARCHAR2(255),
    eventnum NUMBER,
    eventmsgtype NUMBER,
    eventmsgactiontype NUMBER,
    period NUMBER,
    wctimestring VARCHAR2(255),
    pctimestring VARCHAR2(255),
    homedescription VARCHAR2(255),
    neutraldescription VARCHAR2(255),
    visitordescription VARCHAR2(255),
    score VARCHAR2(255),
    scoremargin VARCHAR2(255),
    person1type NUMBER,
    player1_id VARCHAR2(255),
    player1_name VARCHAR2(255),
    player1_team_id VARCHAR2(255),
    player1_team_city VARCHAR2(255),
    player1_team_nickname VARCHAR2(255),
    player1_team_abbreviation VARCHAR2(255),
    person2type NUMBER,
    player2_id VARCHAR2(255),
    player2_name VARCHAR2(255),
    player2_team_id VARCHAR2(255),
    player2_team_city VARCHAR2(255),
    player2_team_nickname VARCHAR2(255),
    player2_team_abbreviation VARCHAR2(255),
    person3type NUMBER,
    player3_id VARCHAR2(255),
    player3_name VARCHAR2(255),
    player3_team_id VARCHAR2(255),
    player3_team_city VARCHAR2(255),
    player3_team_nickname VARCHAR2(255),
    player3_team_abbreviation VARCHAR2(255),
    video_available_flag VARCHAR2(255)
);

-- Tabla temporal para player
CREATE TABLE player_temp (
    id VARCHAR2(255),
    full_name VARCHAR2(255),
    first_name VARCHAR2(255),
    last_name VARCHAR2(255),
    is_active NUMBER
);

-- Tabla temporal para team
CREATE TABLE team_temp (
    id VARCHAR2(255),
    full_name VARCHAR2(255),
    abbreviation VARCHAR2(255),
    nickname VARCHAR2(255),
    city VARCHAR2(255),
    state_ VARCHAR2(255),
    year_founded NUMBER
);

-- Tabla temporal para team_details
CREATE TABLE team_details_temp (
    team_id NUMBER,
    abbreviation VARCHAR2(10),
    nickname VARCHAR2(50),
    yearfounded VARCHAR(100),
    city VARCHAR2(100),
    arena VARCHAR2(100),
    arenacapacity VARCHAR2(100),
    owner VARCHAR2(100),
    generalmanager VARCHAR2(100),
    headcoach VARCHAR2(100),
    dleagueaffiliation VARCHAR2(100),
    facebook VARCHAR2(200),
    instagram VARCHAR2(200),
    twitter VARCHAR2(200)
);

-- Tabla temporal para team_history
CREATE TABLE team_history_temp (
    team_id VARCHAR2(255),
    city VARCHAR2(255),
    nickname VARCHAR2(255),
    year_founded NUMBER,
    year_active_till NUMBER
);

-- Tabla temporal para team_info_common
CREATE TABLE team_info_common_temp (
    team_id VARCHAR2(255),
    season_year VARCHAR2(255),
    team_city VARCHAR2(255),
    team_name VARCHAR2(255),
    team_abbreviation VARCHAR2(255),
    team_conference VARCHAR2(255),
    team_division VARCHAR2(255),
    team_code VARCHAR2(255),
    team_slug VARCHAR2(255),
    w NUMBER,
    l_ NUMBER,
    pct NUMBER,
    conf_rank NUMBER,
    div_rank NUMBER,
    min_year NUMBER,
    max_year NUMBER,
    league_id VARCHAR2(255),
    season_id VARCHAR2(255),
    pts_rank NUMBER,
    pts_pg NUMBER,
    reb_rank NUMBER,
    reb_pg NUMBER,
    ast_rank NUMBER,
    ast_pg NUMBER,
    opp_pts_rank NUMBER,
    opp_pts_pg NUMBER
);
