SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE FORCE LOGGING;
ALTER DATABASE OPEN;

ALTER SYSTEM SET DB_RECOVERY_FILE_DEST='/opt/oracle/oradata/recovery_area' SCOPE=SPFILE;
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST_SIZE=10G SCOPE=SPFILE;

ALTER SYSTEM SET LOG_ARCHIVE_CONFIG='DG_CONFIG=(ORCLCDB,STBY)' SCOPE=BOTH;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1='LOCATION=USE_DB_RECOVERY_FILE_DEST VALID_FOR=(ALL_LOGFILES,ALL_ROLES) DB_UNIQUE_NAME=ORCLCDB' SCOPE=BOTH;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_2='SERVICE=STBY LGWR ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=STBY' SCOPE=BOTH;
ALTER SYSTEM SET FAL_SERVER=STBY SCOPE=BOTH;
ALTER SYSTEM SET DB_FILE_NAME_CONVERT='/opt/oracle/oradata/STBY','/opt/oracle/oradata/ORCLCDB' SCOPE=SPFILE;
ALTER SYSTEM SET LOG_FILE_NAME_CONVERT='/opt/oracle/oradata/STBY','/opt/oracle/oradata/ORCLCDB' SCOPE=SPFILE;
ALTER SYSTEM SET STANDBY_FILE_MANAGEMENT=AUTO SCOPE=BOTH;
ALTER SYSTEM SET DG_BROKER_CONFIG_FILE1='/opt/oracle/oradata/ORCLCDB/dr1ORCLCDB.dat' SCOPE=BOTH;
ALTER SYSTEM SET DG_BROKER_CONFIG_FILE2='/opt/oracle/oradata/ORCLCDB/dr2ORCLCDB.dat' SCOPE=BOTH;
ALTER SYSTEM SET DG_BROKER_START=TRUE SCOPE=BOTH;

CREATE USER C##DGADMIN IDENTIFIED BY dgpass;
GRANT CONNECT, RESOURCE, SYSOPER, SYSDBA TO C##DGADMIN CONTAINER=ALL;
