CREATE SEQUENCE city_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE estadium_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE state_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE countries_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE teams_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE quarter_score_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE overtime_score_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE id_draft START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE paises START WITH 1;

CREATE SEQUENCE seq_combine_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_physical_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_athletic_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_shooting_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pbp_player_id START WITH 1 INCREMENT BY 1;

