services:
  oracle-master:
    container_name: oracle_master
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Hola1234!
    volumes:
      - oracle_master_data:/opt/oracle/oradata
      - ./oracle-config/master:/container-init-config
    command: [ "/container-init-config/init-network-config.sh" ]
    networks:
      - oracle_network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: 5g

  oracle-standby:
    container_name: oracle_standby
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    ports:
      - "1522:1521"
      - "5501:5500"
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=STBYPDB1
      - ORACLE_PWD=Hola1234!
    volumes:
      - oracle_standby_data:/opt/oracle/oradata
      - ./oracle-config/standby:/container-init-config
    command: [ "/container-init-config/init-network-config.sh" ]
    networks:
      - oracle_network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: 4g

volumes:
  oracle_master_data:
  oracle_standby_data:

networks:
  oracle_network:
    driver: bridge
