SHUTDOWN IMMEDIATE;
STARTUP NOMOUNT;

ALTER SYSTEM SET DB_RECOVERY_FILE_DEST='/opt/oracle/oradata/recovery_area' SCOPE=SPFILE;
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST_SIZE=10G SCOPE=SPFILE;


ALTER SYSTEM SET db_name='ORCLCDB' SCOPE=SPFILE;
ALTER SYSTEM SET db_unique_name='STBY' SCOPE=SPFILE;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1='LOCATION=USE_DB_RECOVERY_FILE_DEST VALID_FOR=(ALL_LOGFILES,ALL_ROLES) DB_UNIQUE_NAME=STBY' SCOPE=SPFILE;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_2='SERVICE=ORCLCDB ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=ORCLCDB' SCOPE=SPFILE;
ALTER SYSTEM SET LOG_ARCHIVE_CONFIG='DG_CONFIG=(ORCLCDB,STBY)' SCOPE=BOTH;
ALTER SYSTEM SET FAL_SERVER=ORCLCDB SCOPE=BOTH;
ALTER SYSTEM SET FAL_CLIENT='STBY' SCOPE=SPFILE;
ALTER SYSTEM SET DB_FILE_NAME_CONVERT='/opt/oracle/oradata/ORCLCDB','/opt/oracle/oradata/STBY' SCOPE=SPFILE;
ALTER SYSTEM SET LOG_FILE_NAME_CONVERT='/opt/oracle/oradata/ORCLCDB','/opt/oracle/oradata/STBY' SCOPE=SPFILE;
ALTER SYSTEM SET STANDBY_FILE_MANAGEMENT=AUTO SCOPE=SPFILE;
