FROM bitnami/postgresql-repmgr:15

USER root

RUN install_packages wget tar && \
    wget https://github.com/wal-g/wal-g/releases/download/v3.0.7/wal-g-pg-ubuntu-20.04-amd64.tar.gz && \
    tar -xzf wal-g-pg-ubuntu-20.04-amd64.tar.gz && \
    mv wal-g-pg-ubuntu-20.04-amd64 /usr/local/bin/wal-g && \
    chmod +x /usr/local/bin/wal-g && \
    rm -f wal-g-pg-ubuntu-20.04-amd64.tar.gz

USER 1001
